- name: general | Update package cache
  community.general.pkgin:
    update_cache: yes
  
- name: general | Full package upgrade
  community.general.pkgin:
    full_upgrade: yes

- name: general | Install packages
  command:
    cmd: /opt/local/bin/pkgin -y in ca-certificates nsd unbound

- name: unbound | Unbound control setup
  command:
    cmd: /opt/local/sbin/unbound-control-setup

- name: nsd | nsd control setup
  command:
    cmd: /opt/local/sbin/nsd-control-setup

- name: unbound | Copy main Unbound configuration file
  template:
    mode: 0644
    src: unbound.j2
    dest: /opt/local/etc/unbound/unbound.conf

- name: nsd | copy main nsd config file
  template:
    mode: 0644
    src: nsd.j2
    dest: /opt/local/etc/nsd/nsd.conf

- name: unbound | Copy adblock script
  copy:
    mode: 0644
    src: adblock-update
    dest: /opt/local/bin/adblock-update

- name: unbound | Create unbound log directory
  file:
    mode: 0755
    path: /var/log/unbound
    state: directory
    owner: unbound
    group: unbound

- name: unbound | Start Unbound
  service:
    name: unbound
    state: restarted
    enabled: yes

- name: nsd | Start nsd
  service:
    name: nsd
    state: restarted
    enabled: yes
